import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import ReactQueryProvider from "./components/ReactQueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <ReactQueryProvider>
            <div className="flex h-screen container m-auto flex-col justify-between pl-10 pr-10">
              {/* <Header /> */}
              {children}
              {/* <Footer /> */}
            </div>
          </ReactQueryProvider>
        </Providers>
      </body>
    </html>
  );
}
